language: node_js

node_js:
  - "8.10"

services:
  - docker

# env:
#   global:
  

before_install:
  - npm i -g mocha nyc 

install:
  - npm i 

script: 
  - npm test 
  # - docker-compose up --build

deploy:
  provider: script
  script: bash cicd/docker_push
  on:
    branch: master  
  